# Generated by Django 4.2.4 on 2023-08-20 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_post_comments_comments_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_2',
        ),
    ]
