# Generated by Django 4.2.4 on 2023-08-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_invoice_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='id',
        ),
        migrations.AddField(
            model_name='store',
            name='item_id',
            field=models.CharField(default='082423', editable=False, max_length=6, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
