# Generated by Django 4.2.4 on 2023-08-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_invoice_item_id_invoice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='item_id',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
