# Generated by Django 4.2.4 on 2023-08-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_invoice_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='item_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
