# Generated by Django 4.2.4 on 2023-08-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_invoice_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_number',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='item_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
