# Generated by Django 4.2.4 on 2023-08-29 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_invoice_invoice_number_alter_invoice_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
    ]
