# Generated by Django 4.2.4 on 2023-10-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_subscription_end_date_membershiptoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptoken',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
